#!/bin/bash

set -eou pipefail


readonly SEED=2363

readonly TRAIN_TSV="data/TestData/kataEng_T_train.tsv"

readonly RANDOM_STARTS=25

readonly MODEL_SIZE="${MODEL_SIZE:-1000000}"

readonly FAR_PATH="models/kataEng.far"

readonly ENCODER_PATH="models/kataEng.enc"

readonly FST_PATH="models/kataEng.fst"

readonly ORDER="${ORDER:-8}"

readonly PRUNING_METHOD="${PRUNING_METHOD:-relative_entropy}"

readonly SMOOTHING_METHOD="${SMOOTHING_METHOD:-kneser_ney}"


./align.py \
        --seed="${SEED}" \
        --random_starts="${RANDOM_STARTS}" \
        --tsv_path="${TRAIN_TSV}" \
        --encoder_path="models/kataEng.enc" \
        --far_path="models/kataEng.far"


model() {
    ngramcount --require_symbols=false --order="${ORDER}" "${FAR_PATH}" | \
        ngrammake --method="${SMOOTHING_METHOD}" - | \
        ngramshrink \
            --method="${PRUNING_METHOD}" \
            --target_number_of_ngrams="${MODEL_SIZE}" \
            - | \
        fstencode --decode - ${ENCODER_PATH} "${FST_PATH}"
}

model
